Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -2,8 +2,6 @@ name: Build firmware
 
 on:
   workflow_dispatch:
-  schedule:
-    - cron: '0 0 * * *'  # Запуск каждый день в 00:00 UTC
   push:
     tags:
       - '*'
@@ -50,21 +48,21 @@ jobs:
     - name: Build firmware
       run: |
         cp build.config padavan-ng/trunk/.config
-        pushd padavan-ng/trunk
+        cd padavan-ng/trunk
         ./clear_tree.sh
         ./build_firmware.sh
-        popd
+
+        FW_FILE_NAME="$(find images -type f -regextype posix-extended -iregex ".*\.(trx|bin)$" \
+                        -printf "%T@\t%f\n" | sort -V | tail -1 | cut -f2)"
+        [[ -n $FW_FILE_NAME ]] || { echo "Firmware file not found"; exit 1; }
+        echo "FW_FILE_NAME=$FW_FILE_NAME" >> $GITHUB_ENV
 
     - name: Run custom post-build script
       run: '[[ -f post-build.sh ]] && . post-build.sh || :'
 
     - name: Prepare artifacts
       run: |
-        FW_FILE_NAME="$(find padavan-ng/trunk/images -type f -regextype posix-extended -iregex ".*\.(trx|bin)$" \
-                        -printf "%T@\t%f\n" | sort -V | tail -1 | cut -f2)"
         cp "padavan-ng/trunk/images/$FW_FILE_NAME" .
-        
-        echo "FW_FILE_NAME=$FW_FILE_NAME" >> $GITHUB_ENV
         echo "BUILD_TIMESTAMP=$(date '+%Y.%m.%d_%H.%M.%S')" >> $GITHUB_ENV
 
     - name: Upload artifacts
@@ -74,7 +72,7 @@ jobs:
         retention-days: 7
         path: |
           ${{ env.FW_FILE_NAME }}
-
+          build.config
     - name: Create Release
       id: create_release
       uses: actions/create-release@v1
@@ -82,7 +80,7 @@ jobs:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         tag_name: release-${{ env.BUILD_TIMESTAMP }}
-        release_name: MI MINI (${{ env.BUILD_TIMESTAMP }})
+        release_name: MI MINI <hadzhioglu> (${{ env.BUILD_TIMESTAMP }})
         body: ''
         draft: false
         prerelease: false
@@ -108,3 +106,4 @@ jobs:
           max_fw_size_fmtd="$(numfmt --grouping "$max_fw_size") bytes"
           echo "Firmware size ($fw_size_fmtd) exceeds max size ($max_fw_size_fmtd) for your target device"
           exit 1
+        fi
